version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.17
    - image: circleci/postgres:9.6-alpine
      environment: # environment variables for primary container
        POSTGRES_USER: postgres
    working_directory: /go/src/github.com/pscarmapgithub/PS
    steps:
    - checkout
    - run:
        name: Update certificates
        # command: sudo apt-get --allow-releaseinfo-change update && apt upgrade -y
        # command: sudo apt-get --allow-releaseinfo-change update && sudo apt-get install --reinstall ca-certificates
        command: sudo apt update && sudo apt install ca-certificates libgnutls30 -y
    - run:
        name: Get all dependencies
        command: |
          # go mod tidy
          # go mod download
          go get -v ./...
          go get -u github.com/onsi/ginkgo/ginkgo
        # go get -u github.com/onsi/gomega/...
    - run:
        name: Test everything
        command: ginkgo -r -race -failFast -progress
    # - setup_remote_docker:
    #     docker_layer_caching: true
    # - run:
    #     name: build and push Docker images
    #     shell: /bin/bash
    #     command: |
    #       chmod +x ./build.sh
    #       ./build.sh





